# 워커 프로레스 수
# CPU 코어 수 만큼 자동으로 워커 생성
# 워커 - 일하는 사람 -> CPU 코어 수 만큼 일하는 사람 부여
worker_processes auto;

events {
    # 워커 하나당 동시에 처리할 수 있는 최대 연결 수
    worker_connections 1024;
}

# HTTP 관련 설정
http{
    # 파일 타입 자동 매핑
    include mime.types;
    # 리버스 프록시 캐시 설정
    proxy_cache_path /var/cache/nginx 
                    levels=1:2 
                    keys_zone=my_cache:100m 
                    max_size=10g # 캐시 저장 용량
                    inactive=60m # 캐시 보유 시간
                    use_temp_path=off;
    # 로드 벨런싱 하는 부분
    upstream py_server{
        # ip_hash; 
        # location/py에서 넘겨받음 /posts
        server 192.168.0.26:5000; #조창제
        # 192.168.0.26:5000/posts
        server 192.168.0.32:5000; #세덕님
        # 192.168.0.26:5000/posts
        server 192.168.0.19:5000; #관홍님
        # 192.168.0.26:5000/posts
    }

    server{
        # frontend build파일로 웹서비스 구동되는 부분
        # 80번 포트로 접근하면 /app/build 파일 실행해라
        listen 80;
        server_name localhost;
        root /app/build;
        index index.html;

        location /py {
            # 요청 주소에서 /py 삭제
            rewrite ^/py(/.*)$ $1 break;
            # http://localhost:80/posts
            # /posts
            proxy_pass http://py_server;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }



        location /files {
            alias /app/files/;
            autoindex on;
            allow all;
        }

       location /{
            # uri : 요청된 URL의 경로 localhost/test -> /test 
            # try_files 목록들: 순서대로 요청해봐라
            try_files $uri $uri/ /index.html;
        }
        
        location /test {
            proxy_pass http://192.168.76.19:3000;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}